#! /bin/bash

temp1=$(mktemp  tmp.XXXXXX)
temp2=$(mktemp  tmp.XXXXXX)

diskspace() {
	df -k >$temp1
	dialog --textbox $temp1 20 60
}

whoseon() {
	who >$temp1
	dialog --textbox $temp1 20 50
}
memusage() {
	cat /proc/meminfo > $temp1 
	dialog --textbox $temp1 20 50	
}
while [ 1 ]
do
dialog --menu "sys admin menu" 20 30 10 1 "Display disk space" 2 "Display users" 3 "Display memory" 4 "Exit" 2> $temp2
if [ $? -eq 1 ] ;then break; fi
selection=`cat $temp2`
case $selection in
	1) 
		diskspace ;;
	2) 
		whoseon ;;
	3) 
		memusage ;;
	4)
		clear 
		break ;;
esac
done
rm -f $temp1 2> /dev/null
rm -f $temp2 2> /dev/null


